- name: configure frontend server
  hosts: frontend
  become: yes
  tasks:
    - name: Install nginx server
      ansible.builtin.package:
        name: nginx
        state: present
    
    - name: Start njinx server
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes
    
    - name: remove default html directory
      ansible.builtin.file:
        path: /usr/share/nginx/html
        state: absent 
    
    - name: create html directory
      ansible.builtin.file:
        path: /usr/share/nginx/html
        state: directory
    
    - name: download the frontend code
      ansible.builtin.get_url:
        url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
        dest: /tmp/frontend.zip 

    - name: extract the code
      ansible.builtin.unarchive:
        src: /tmp/frontend.zip # by default ansible
        dest: /usr/share/nginx/html
        remote_src: yes

    - name: copy expense conf 
      ansible.builtin.copy:
        src: expense.conf 
        dest: /etc/nginx/default.d/expense. 

    - name: restart njinx
      ansible.builtin.service:
        name: nginx
        state: restarted